/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Wylie2_anims.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Wylie2_anims.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {

    if(props.action && typeof actions[props.action] !== 'undefined'){

      actions[props.action]?.play()

    }

  }, [props, actions]);

  return (

    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Mesh_0" geometry={nodes.Mesh_0.geometry} material={materials.Material_0} skeleton={nodes.Mesh_0.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Wylie2_anims.glb')
